[package]
name = "mriynyk-merkle"
description = "Merkle tree utilities."
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mriynyk/merkle-tree-rs"
homepage = "https://github.com/mriynyk/merkle-tree-rs"
readme = "README.md"
keywords = ["merkle-tree", "merkle-proof", "no-std", "blockchain", "zk"]
categories = [
    "cryptography",
    "cryptography::cryptocurrencies",
    "data-structures",
    "no-std",
    "no-std::no-alloc",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]

[dev-dependencies]
sha3 = "0.12.0"
sha2 = "0.11.0"
light-poseidon = "0.4.0"
ark-ff = "0.5.0"
ark-bn254 = "0.5.0"

[features]
default = []
alloc = []
std = ["alloc"]

[[example]]
name = "keccak256_positional"
required-features = ["alloc"]

[[example]]
name = "keccak256_commutative"
required-features = ["alloc"]

[[example]]
name = "sha256"
required-features = ["alloc"]

[[example]]
name = "poseidon"
required-features = ["alloc"]

[[example]]
name = "domain_separated"
required-features = ["alloc"]
