[package]
name = "mriynyk-merkle-cli"
description = "Command-line tool for working with Merkle trees on EVM."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["merkle", "merkle-tree", "evm", "ethereum", "cli"]
categories = ["command-line-utilities", "cryptography::cryptocurrencies"]


[dependencies]
mriynyk-merkle = { workspace = true }

[[bin]]
name = "merkle"
path = "src/main.rs"
