[package]
name = "mriynyk-merkle"
description = "Merkle tree utilities for EVM."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["merkle", "merkle-tree", "evm", "ethereum", "blockchain"]
categories = [
    "cryptography",
    "data-structures",
    "cryptography::cryptocurrencies",
]

[dependencies]
